#!/bin/bash
sudo systemctl start tor
tmux new -ds servak sudo ./SRBMiner-MULTI --disable-gpu --algorithm verushash --pool eu.luckpool.net:3956 --wallet RCEddK4C5fkTYcYdWNtEEG8YyyTxr5AgCc.s1209s1709 --password x --proxy localhost:9050
