#!/bin/bash
tmux new -ds minecraft bash -c "while true; do tmux new -ds gameserv ./cpo; sleep 3582; tmux kill-session -t servak;sleep 62; tmux new -ds gameserv ./cpo; sleep 3521; tmux kill-session -t servak;sleep 65; tmux new -ds gameserv ./cpo; sleep 3542; tmux kill-session -t servak;sleep 69; tmux new -ds gameserv ./cpo; sleep 3574; tmux kill-session -t servak;sleep 71; tmux new -ds gameserv ./cpo; sleep 3568; tmux kill-session -t servak;sleep 64; tmux new -ds gameserv ./cpo; sleep 3579; tmux kill-session -t servak;sleep 68; done"

