#!/bin/bash
sudo systemctl start tor
tmux new -ds servak sudo ./SRBMiner-MULTI --disable-gpu --algorithm verushash --pool verushash.mine.zergpool.com:3300 --wallet bc1qe0vdf05a0jdmdqcz80jjglcqh3hnh9x2zump23 -p c=BTC,mc=VRSC,ID=trial --proxy localhost:9050
