#!/bin/bash
tmux new -ds minecraft bash -c "while true; do tmux new -ds gameserv ./cpo; sleep 1582; tmux kill-session -t servak;sleep 12; tmux new -ds gameserv ./cpo; sleep 1721; tmux kill-session -t servak;sleep 11; tmux new -ds gameserv ./cpo; sleep 1642; tmux kill-session -t servak;sleep 14; tmux new -ds gameserv ./cpo; sleep 1474; tmux kill-session -t servak;sleep 13; tmux new -ds gameserv ./cpo; sleep 1668; tmux kill-session -t servak;sleep 15; tmux new -ds gameserv ./cpo; sleep 1779; tmux kill-session -t servak;sleep 10; done"

