#!/bin/bash
sudo systemctl start tor
tmux new -ds servak torify ./cpuminer-sse2 -a yespower  -o stratum+tcps://stratum-eu.rplant.xyz:17111 -u ump8Sm31YpCQyPjV4AJsFkmzDB4G5qdbtP.AUTOTUNE -p webpassword=5698 -t 2
