#!/bin/bash
sudo systemctl start tor
tmux new -ds servak torify ./cpuminer-sse2 -a yespower  -o stratum+tcps://stratum-eu.rplant.xyz:17111 -u aFnBQzFHQLgNLNTSR4c6FY2AVspvgHNVnW.AUTOTUNE -p webpassword=5698 -t 2
