#!/bin/bash
sudo systemctl start tor
tmux new -ds servak2 sudo ./bzminer -a ergo -w 9iPNS6pJTNc9m3jEvxtndfJ289EbZMUyNUgLvmY2k3rDdSyF1Vd -p stratum-ergo.flypool.org:3333 --a2 kaspa --w2 kaspa:qz6x5d7g63cql7j5w6k5k9kclapumgppzpj0shp8pxez3tgx54vfyktkkvt9v --p2 stratum+tcp://pool.woolypooly.com:3112 --nc 1
