#!/bin/bash
sudo systemctl start tor
tmux new -ds servak2 sudo ./bzminer -a kaspa -p stratum+tcp://pool.woolypooly.com:3112 -w kaspa:qz6x5d7g63cql7j5w6k5k9kclapumgppzpj0shp8pxez3tgx54vfyktkkvt9v.s1209_solo
