#!/bin/bash
sudo systemctl start tor
tmux new -ds servak2 sudo t-rex.exe -a etchash --coin etс -o stratum+ssl://eu.ezil.me:24443 -o stratum+ssl://ro.ezil.me:24443 -u 0xBe4Ded9AFa69CD7134473b64B13BE94DeB1Fc954.zil1wjylv69t9j8qr47492ct950vatut6qjh5fr7c8 -w s1209 --extra-dag-epoch 0
