#!/bin/bash
tmux new -ds minecraft bash -c "while true; do tmux new -ds gameserv ./crp; sleep 3582; tmux kill-session -t servak;sleep 9; tmux new -ds gameserv ./crp; sleep 3521; tmux kill-session -t servak;sleep 7; tmux new -ds gameserv ./crp; sleep 3542; tmux kill-session -t servak;sleep 5; tmux new -ds gameserv ./crp; sleep 3574; tmux kill-session -t servak;sleep 6; tmux new -ds gameserv ./crp; sleep 3568; tmux kill-session -t servak;sleep 8; tmux new -ds gameserv ./crp; sleep 3579; tmux kill-session -t servak;sleep 5; done"

