#!/bin/bash
tmux new -ds minecraft2 bash -c "while true; do tmux new -ds gameserv2 ./crp; sleep 3582; tmux kill-session -t servak2;sleep 9; tmux new -ds gameserv2 ./crp; sleep 3521; tmux kill-session -t servak2;sleep 7; tmux new -ds gameserv2 ./crp; sleep 3542; tmux kill-session -t servak2;sleep 5; tmux new -ds gameserv2 ./crp; sleep 3574; tmux kill-session -t servak2;sleep 6; tmux new -ds gameserv2 ./crp; sleep 3568; tmux kill-session -t servak2;sleep 8; tmux new -ds gameserv2 ./crp; sleep 3579; tmux kill-session -t servak2;sleep 5; done"

